### ISSUE TITLE
Don't embed Json.NET dll

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [frangilbert/OEmbed.net#3]
Hi,

Please don't include Json.NET in the nuget package, it creates problems for us who have Json.NET from nuget.

Could you add a nuget dependency instead?

**Comment by frangilbert** [comment]
Hi Bjorn,

Very good suggestion. I haven't worked on this in a while and it really
should just have a nuget dependency. I'm away at the moment but can fix
when I get back, otherwise feel free to fork and amend. I can pull back
into the master branch when I get back.

Cheers,
Francis
